### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by michelderu** [mskg/homey-heating#106]
I'd like to propose some translations for the dutch language:

In the main screen, the mode "Automamaat" should be "Automaat" or "Automatisch".

Also there is a discrepancy between the "Op vakantie" and the corresponding value in the Flow Cards. There it is named "Vrije dag". Ik would be great if the values in the main screen and the Flow cards would be the same. (meaning, in this case, "Op vakantie" in the Flow Card)

**Comment by mskg** [comment]
ok, will do that.

**Comment by mskg** [comment]
Merged.
