### ISSUE TITLE
Copy a current schedule gives an error

### ISSUE THREAD

**Issue by jaxc0402** [mskg/homey-heating#108]
![IMG_0898](https://user-images.githubusercontent.com/18361873/61707996-01c02480-ad4c-11e9-88d1-9af59f467aba.jpeg)

**Describe the bug**
Copy a current schedule gives an error

**To Reproduce**
1. Go to a existing schedule
2. Click on copy and give it a name... then OK

3. See error (picture attached)

I can confirm I can reproduce

**Expected behavior**
Just copy the schedule

**Screenshots**
see above

**Smartphone (please complete the following information):**
 - Device: Iphone X
 - OS: IOS 13
 - Version homey : 2.5.0-rc.6

**Additional context**

**Comment by mskg** [comment]
Cannot reproduce this. Feel free to open again if it happens > 1.2.2
