### ISSUE TITLE
Virtual Thermostat does not report correct 'current temperature'

### ISSUE THREAD

**Issue by Eternity-again** [mskg/homey-heating#118]
**Describe the bug**
I have a zone with a VThermostat (App "VThermo" by Bjømar Almili) and it gives correct feedback of the two temp sensors (Aqua) and the setpoint I created in the Heating Plan Scheduler (HPS)"

![Screenshot_20191030-192635](https://user-images.githubusercontent.com/10754229/67954914-02d9db00-fbf2-11e9-9c53-a905098e03e3.png)

I added a Virtual Thermostaat via HPS to the plan ‘Plan WK (=Living room Plan)’.
the devise shows incorrect information. It will show the correct setpoint of the room (but sometimes not), but the measured temperature is incorrect:

![Screenshot_20191030-192734](https://user-images.githubusercontent.com/10754229/67954932-09685280-fbf2-11e9-8658-706fead81c26.png)

**Expected behavior**
I would think that all thermostats (VThermo or does added via your App) in the same zone with the same devices would report the same measured temperature.

**Screenshots**

**Smartphone (please complete the following information):**
 - Motorola
 - G6+ 
- Latest Homey f/w (3.0.0)

**Comment by mskg** [comment]
Should be fixed by #96, #95. If this is not resolved in 1.2.2 please reopen the issue.
