### ISSUE TITLE
not ready errors after homey restart

### ISSUE THREAD

**Issue by maja2020** [mskg/homey-heating#120]
**Describe the bug**
The app tries to send temperature schedule values to devices. I receive notifications on the timeline with  (not_ready) errors. Every reboot of my homey will produce these errors.

My valves use zwave, I think the app tries to send data but the network isn't ready yet. It is not a big deal, may be it is possible to force a retry in a few minutes? Or just wait a minute after app start when Homey has been rebooted. 

![afbeelding](https://user-images.githubusercontent.com/32190313/68549762-2247e380-03fc-11ea-8807-21cf432b2e35.png)

**Comment by Baldhor** [comment]
I got the same issue and currently I lose current (electricity) quite often (electrician supposed to change whatever to solve it) ... very annoying to be honest :(

**Comment by mskg** [comment]
Bumping dependencies solves this issue.
