### ISSUE TITLE
What does the badges of Virtual Thermostat display

### ISSUE THREAD

**Issue by dolfje** [mskg/homey-heating#135]
Hey,

I'm not totally understanding what the virtual thermostat is displaying on the devices list. I guess it should display the target temperature and the blue/red show if it is cooling or warming. Is that correct?

But I have the following problem. Is have 9 different thermostats and created 9 plans and thus 9 virtual thermostats. On the image you see on the bottom the thermostats and on the top the corresponding virtual thermostat.

![Screenshot_20191208-233253](https://user-images.githubusercontent.com/2472049/70398188-1fe7a200-1a19-11ea-98f1-46c622122ba7.jpg)
So for example, the Plan bureau is the virtual thermostat of the Thermostat Bureau. Here you can see that both are 15°, what is the target temperature. And the virtual thermostat it's temperature is 4° (and thus shows it should heat), while the correct value is 18.8° and is shown in the normal thermostat (and thus shows blue, like it should).

And a little bit later when I reopen the page, I see the following:
![Screenshot_20191209-001939](https://user-images.githubusercontent.com/2472049/70398277-009d4480-1a1a-11ea-8a9b-4d0a34f7e1a9.jpg)
So here most virtual thermostats show 4° and 22°. The plans were not adapted and the values in the plans are 18° and 20°. So I have no idea about 4 and 22. Also the current temperature is the same as the target temperature now. Luckily the normal thermostats are still using the correct values.

What is happening and what should be the normal values?

Maybe interesting to know, the devices are on 'fully manual'. But I have seen strange behaviors also with automatic

**Comment by mskg** [comment]
Workarround in #138
