### ISSUE TITLE
Current Temperature not reflecting actual value

### ISSUE THREAD

**Issue by Antch1** [mskg/homey-heating#137]
Hello, the app is great but it seems there's no update of the current temp. I have 8 spirit valves and everything works well except i cannot read the room temperature from the virtual thermo. When opening the virtual thermostat, current value never change. I have to reboot the app to get the latest value. same in the current temperature page of the app settings. When i open any valve page i have the latest room temp, i can see it very precisely via insight.

Does anybody had the same issue ? Is it already known ?

Thank you.

**Comment by mskg** [comment]
If you do it once, does it work afterwards?

**Comment by Antch1** [comment]
Since last reboot, values seems to follow. Let me check it during the next 24 hours and i will get back to you.
Thanks a lot for your work !


Le jeu. 12 déc. 2019 à 21:49, Markus <notifications@github.com <mailto:notifications@github.com>> a écrit :
If you do it once, does it work afterwards?

**Comment by mskg** [comment]
Are you willing to help with the French translation? :)

**Comment by Antch1** [comment]
Yes why not, I will check anything you sent me and tell you if this is « good french » ;)

**Comment by mskg** [comment]
Workaround in #138
