### ISSUE TITLE
translation issue

### ISSUE THREAD

**Issue by rywr** [mskg/homey-heating#141]
I found a wrong translation in app settings (changing an entry in heating plan).
In german, it should be "Speichern" instead of "Sparen".

![Screenshot_20191219-185628_Homey](https://user-images.githubusercontent.com/49495550/71197590-3bad3c80-2292-11ea-8dbe-29022de93c18.jpg)

I hope, this is the right place for transaltion issues. Or do you have a forum thread for this app to report such issues?

**Comment by mskg** [comment]
Perfect here.

**Comment by rywr** [comment]
Hi Markus,

**Comment by rywr** [comment]
Hi

**Comment by rywr** [comment]
Hi Markus,
sorry, it was autosaved twice while searching for my screenshots...

I have tho other proposals for german translation:

1)
![Screenshot_20191219-192340_Homey](https://user-images.githubusercontent.com/49495550/71202114-ca728700-229b-11ea-828d-d92cb273af01.jpg)
Instead of "Wirtschaft" I would prefer "wirtschaftlich" (economic) or "ökonomisch'.
If you prefer a noun, then "Sparen" would be better (here it is right :-)), but the adjective would be better to understand.

2)
![20191219_192526](https://user-images.githubusercontent.com/49495550/71202175-f1c95400-229b-11ea-9263-68c45609a2d4.jpg)
This should be "Uhrzeit" (time of day) or just "Zeit" (time).

**Comment by mskg** [comment]
Checked the files, and that changes already made it to the next release. If you're willing, you can quickly check the primary file https://github.com/mskg/homey-heating/blob/check-devices/locales/de.json

**Comment by rywr** [comment]
All translations are fine. Thanks for your quick adjustments.
