### ISSUE TITLE
Setting virtual thermostat manuals and then setting it back to automatic doesn’t make the virtual thermostat go back to automatic state again

### ISSUE THREAD

**Issue by mruiter** [mskg/homey-heating#145]
First floor has a active heating plan .

Flows on the first floor
First flow acting on alarm of windows opening sets the virtual thermostat to 13 degrees . This making the virtual thermostat go to manual mode until midnight 

Second flow that starts when the windows alarm goes off sets the virtual thermostat back to automatic mode.

This doesn’t happen and the virtual thermostat stays on manual until midnight 

When I open the virtual thermostat in devices and switch it manual back to automatic it works again and the heating plan gets activated again and goes back to the in the schedule defined temperature 

So the flow card for virtual thermostat switch back to automatic mode doesn’t work for me

**Comment by mruiter** [comment]
![D5F6BBCB-C444-4905-A5C7-B7102622FB06](https://user-images.githubusercontent.com/17739535/71643209-d9ebca00-2cb6-11ea-9df0-297533c59993.png)
![2F2B815A-C798-443D-8573-3828B0DA1164](https://user-images.githubusercontent.com/17739535/71643210-d9ebca00-2cb6-11ea-81ce-e454e666b1f5.png)


You can see in the notifications that the flow has runned but the second pictures shows the virtual thermostat and that it’s still on manual

**Comment by mskg** [comment]
Understood. I will check that.

**Comment by mskg** [comment]
Can you please also post screenshots of your flows?

**Comment by mruiter** [comment]
![F1952F55-F54D-4FA1-806D-1624DD5CA659](https://user-images.githubusercontent.com/17739535/71643511-03a6f000-2cbb-11ea-8d1c-8ac9df6ccd0e.png)
![A60D8BA2-A9E0-41A0-BE6B-375FE6C9CA48](https://user-images.githubusercontent.com/17739535/71643512-03a6f000-2cbb-11ea-9e3a-e5c447284ffd.png)


They are really simple

First just sets the virtual thermostat to 13 an by doing so it sets it also to manual until midnight mode 

The second flow gets triggered when all Windows are closed again and should put the virtual thermostat back to automatic and set it to the temperatures that the schedule that’s active on that floor should demand but it stays on manual until midnight

**Comment by mruiter** [comment]
Lol thnx for the support . Now that I post the screenshots I see what I have missed . I set the schedule to automatic and not the virtual thermostat .

To much drinks on last night or the fireworks made me stupid 😂

Have a great new year and thank you for you’re great app and support
