### ISSUE TITLE
query for heating mode

### ISSUE THREAD

**Issue by ZimoSka** [mskg/homey-heating#154]
Hi,
I'd like to use heating mode in flows - to be able to query which mode is currently on.

My example is - when I return home and query mode is "one day away from home" do something.
or
when I return home and mode is "out of season" - do nothing.

thanks and btw - great app!

**Comment by mskg** [comment]
It's already in there: You can use the current heating mode in the `AND` condition.

1. Create flow with condition
2. Select And
3. Add Logic
4. Choose `*** is exactly`
5. Search for `Heating` (depends on your language)
6. Select `Heating mode`
7. In the condition you have to enter one of `Automatic`, `1 day at home`, `Sleeping`, ... (depends on your language)

**Comment by ZimoSka** [comment]
thanks for explanation. I was looking for separate card. This is perfect.
sorry for bothering.
