### ISSUE TITLE
Interpretation of console.re record?

### ISSUE THREAD

**Issue by ma-be** [mskg/homey-heating#165]
Hi @mskg,
I would like to use your app which is very promissing. But I am encountering with the bugs others has already reported.
When I am trying monitoring the situation with the console.re, I see the green line appearing regularly. What does it mean exactly? 

![image](https://user-images.githubusercontent.com/11045804/97798861-58443000-1c2a-11eb-93c2-63f3b9c12ff1.png)

I am asking because the device is a netgear router and it looks strange to try to update its "set temperature" 🤔.
Does your app try to set the temperature of this device?
Thanks for the info.

**Comment by mskg** [comment]
Every time you add/change/remove devices the App has to check if the new device can deal with temperature. As it cannot, it is ignored.
This is was the message says.
