### ISSUE TITLE
2023 Support

### ISSUE THREAD

**Issue by StevenRenders** [mskg/homey-heating#173]
Would be nice to have support for Homey Pro 2023

**Comment by mskg** [comment]
I will do the support. I waited for the pro to arrive and do it in one shot - but that didn't work out. Will try to prioritize it as good as I can.

**Comment by Dome0068** [comment]
Hi Markus,
Thank you. I've same request because I need your app working on Homey Early 2023. Let me know

**Comment by daneedk** [comment]
Thanks for you ongoing support Markus!

**Comment by bwa** [comment]
Hi @mskg 

I'm also very dependent of your app. It's simply the best. I cannot really move to the 2023 that I've got now, as a developer.  If you need a hand, just say.

I also migth want to contribute som nice improvement if possible. I really miss to have several time scedules, not only exceptions. In these days you want to have one scheme for expensive prices, and another for cheap prices. Just say the word ...

**Comment by rlucian** [comment]
Hi Markus, any news on the progress? Do you have some timeframe you might share?
All the best!

**Comment by Dome0068** [comment]
Hi Markus, any news on new release for Homey Early 2023?
Thanks and Regards!

**Comment by RonnyWinkler** [comment]
Hi Markus, still waiting for a new version. Your app is the most needed for a warm home and prevents to migrate to the HP23 now.
If you need help with migration please contact us on Slack. There you'll get help for migrating to the new HomeyAPI. Danee had to do this, too and i'm sure he can give you some hints.
Many thanks. Ronny

**Comment by daneedk** [comment]
I’ll absolutely help you when needed concerning the new homey-api, no problem. Just reach out to us on slack as Ronny said.

**Comment by shaarkys** [comment]
It has been almost 4 months since last reply here... I'm giving up ;-(
I tried to contact @mskg Markus also via mail, also no single reply - either something has happened or Markus is really busy by even responding one sentence - which is hard to believe so I think something has happened. I hope he is alright.

**Comment by mskg** [comment]
No need to give up. I'm doing it right now. Will have a first version this week.

**Comment by bwa** [comment]
Nice, if possible look for a possibility to have multiple week plans. I'm thinking about one plan for expensive power, and one for cheap power

**Comment by shaarkys** [comment]
You are great ! Thank you (a pity I just deleted and adjusted all flows but will probably re-do it again ;-) )

**Comment by mskg** [comment]
> Nice, if possible look for a possibility to have multiple week plans. I'm thinking about one plan for expensive power, and one for cheap power

You can already do that. Just make sure only one of them is active at a time. You can use flow to do that for you.

**Comment by mskg** [comment]
> You are great ! Thank you (a pity I just deleted and adjusted all flows but will probably re-do it again ;-) )

There is a backup/restore function in the admin UI ;)

**Comment by bwa** [comment]
> > Nice, if possible look for a possibility to have multiple week plans. I'm thinking about one plan for expensive power, and one for cheap power
> 
> You can already do that. Just make sure only one of them is active at a time. You can use flow to do that for you.

shit, I have missed that ...

Heating Plans ... of cource ... Can create different for same Zone, and switch with a flow. aaaargh

**Comment by mskg** [comment]
https://homey.app/a/app.mskg.homey-heating/test/

Known issues:
- Help link doesn't open
- Navigating forth and back to "Current temperatures" crashes the frontend on the third try

**Comment by RonnyWinkler** [comment]
Hey Markus, many thanks! I'll try on the HP23. But without migration it's not so easy. Perhaps I'll check with some virtual thermostats from HP19 reimported via HomeAssistant.

What exactly does it mean?
_Navigating forth and back to "Current temperatures" crashes the frontend on the third try_

**Comment by mskg** [comment]
> What exactly does it mean?
> Navigating forth and back to "Current temperatures" crashes the frontend on the third try

When you are in the settings area and you choose the different menu options available from the 'burger menu' It might happen that when you select the 'Current temperatures' option the frontend crashes. Just click Done and come back and it works again. Haven't found a reason so far.

**Comment by RonnyWinkler** [comment]
Something that occoured in the old version, too. Perhaps you have an idea how to solve that.

![Screenshot_20230416_195913_Homey.jpg](https://user-images.githubusercontent.com/49495550/232332411-098f3a81-94ce-4a94-90aa-96f18afd8734.jpg)

When selecting a temperature it's not possinle to use the decimal sign.
I have german layout with comma as decimal sign. But it's only possible to click the point. But that's not inserted into the temperature field.
I think it works in an english layout with point as decimal sign.

**Comment by RonnyWinkler** [comment]
I clicked a lot in the menu and got this error message. I hope that can guide you to a possible reason.
![Screenshot_20230416_200437_Homey.jpg](https://user-images.githubusercontent.com/49495550/232332664-b48a463e-1cc8-4cd7-b40f-b0a331506956.jpg)

**Comment by RonnyWinkler** [comment]
One more hint:
I added a new thermostat and it was only found by the app after an app restart. I'm not sure if it was the same in the old version.

**Comment by mskg** [comment]
It's a first working version but there will be some unnoticed things like this. Just report everything and I'll try to fix them one by one.

**Comment by RonnyWinkler** [comment]
Just give us a hint if this issue gets too messed up and we should create single issues for bugs.

I tried to a plan with a thermostat but could not get it to work.
- After saving the plan the thermostat is not changed
- After activating the plan, the thermostat is not changed
- A temperature change im the plan has no effect at set time.

![Screenshot_20230416_212803_Homey.jpg](https://user-images.githubusercontent.com/49495550/232337465-4793b2c8-b7df-4f7a-be5b-6614f29c46ec.jpg)



Any hint how to find the reason? Only debug with a CLI install, right?

**Comment by mskg** [comment]
They adjusted the way how time is handled on the Homey, need some time to figure out consequences. They now always return UTC instead of adjusted to local time.

**Comment by bwa** [comment]
Maybe look at luxon ? It solved time issue in my EasyLogger

**Comment by daneedk** [comment]
I used New Date() in my old code, replaced it with this (lines 1852 and 1853) https://github.com/daneedk/com.uc.heimdall/blob/b2246a67e204e9e3155987b1319a9aa990e1dd34/app.js#L1852
That wil return a localized date time.

**Comment by bwa** [comment]
This is my code :

import { DateTime } from 'luxon';
...
..

init():
    this.timeZone = this.homey.clock.getTimezone();
..
..
..
let ts  = DateTime.now().setZone(this._timezone);


for display this is a little nicer than above

init():
      this.timestampFormat = "dd.MM.yyyy HH.mm.ss";  

let ts_display  = DateTime.now().setZone(this._timezone).toFormat(this._timestampFormat);

**Comment by mskg** [comment]
Bumped to 2.0.2 - fixes all of the mentioned problems above.

**Comment by Dome0068** [comment]
Hello Markus,

Just autoupdated to version 2.0.3 on my Homey Pro Early 2019 but it crashed!
I have restarted the APP but nothing, same behavior: APP crash. In addition I have restarted Homey but nothing, the APP crash!
Please double check and let me know.
I ask if other people have same problem.

**Comment by Dome0068** [comment]
Hello Markus,
Please in the meantime you find and correct the issue can you revert back to previous release?
I have all my termosthat out of scheduling without your app..
Hope you understand.
Thank you!

**Comment by Dome0068** [comment]
I have sent diagnostic report: 402a8d57-4e2d-47ce-ac3a-925b6f22d5ca

**Comment by mskg** [comment]
See #178

**Comment by mskg** [comment]
@Dome0068 please try https://homey.app/a/app.mskg.homey-heating/test/ 
It's hard for me to test as I don't have the hardware to run that specific version.

**Comment by Dome0068** [comment]
Hello Markus,
Help a lot for your prompted response.
I have installed the 2.0.6 test version and now it seems to work back fine.
Only it seems that may Homey is a bit instable, I am noticing disconnession
from Homey phone APP.



Il lun 1 mag 2023, 21:42 Markus ***@***.***> ha scritto:

**Comment by Dome0068** [comment]
Thank you for support Markus

Il lun 1 mag 2023, 22:13 Markus ***@***.***> ha scritto:

**Comment by Dome0068** [comment]
Hello Markus,
I face issue in changing nominal temp on thermostat in fully manual. If I set fully manual on virtual termostat it doesn't reflect on real thermostat. Before (with old version before 2.0.3) it worked fine.
(I am using 2.0.6 sperimental as per your suggestion)
Please let me know

**Comment by mskg** [comment]
Can you please help me understand what that exactly means?

**Comment by Dome0068** [comment]
I guess I made a mistake. Just verified and I tried to apply a fully manual mode on a Plan disabled. Just to confirm: a manual setpoint change  on a virtual thermostat can be made only if the corresponding heating plan is enabled, correct?
