### ISSUE TITLE
Show disabled plas as disabled icon in Devices

### ISSUE THREAD

**Issue by bwa** [mskg/homey-heating#177]
If there is a plan which is disabled, the icon in Devices also should show as disabled.

In this picture belove the Expensive plan is disabled and the Normal plan is active. It's hard to see ...

![image](https://user-images.githubusercontent.com/170977/235197495-f3048fc2-8100-46ce-85ae-ce78b787c102.png)

**Comment by mskg** [comment]
I check that. It's the standard enable, disabled that the device emits. This should be easy.

**Comment by mskg** [comment]
Done in the next update.

**Comment by bwa** [comment]
@mskg 
Yes, the enable/disable is working and seems very fine.

But I didn't expect a disabled plan to actually change the VThermo of that Zone.

In this case, If I open an disabled plan and change the set temeparture it updated the VThermo. Maybe it shouldnt ?

It also calculates the temerature in  the zone wong. see value 11.52

![image](https://user-images.githubusercontent.com/170977/235604954-243c8ab7-21ae-4031-8f65-9b0f1b3eb9ff.png)

**Comment by mskg** [comment]
Hmm ... the plan will not change it automatically because it's disabled. 

If you change it manually - through the temperature dial - the thermostats are adjusted. Everything else would be unnatural because I cannot disable the controls.

**Comment by mskg** [comment]
I will check the calculation

**Comment by bwa** [comment]
> Hmm ... the plan will not change it automatically because it's disabled.
> 
> If you change it manually - through the temperature dial - the thermostats are adjusted. Everything else would be unnatural because I cannot disable the controls.

Maybe you can 'omit' the action, and dont change if disabled.

Anyway, I normally would not do such a thing, but others migth do

**Comment by bwa** [comment]
Using 10.0.0.r90, and lot of strange thing happens

When I'm toggelig a plan
![image](https://user-images.githubusercontent.com/170977/235632637-7cc2bb7b-c8c4-4531-8a2c-d45e93ff3292.png)
![image](https://user-images.githubusercontent.com/170977/235633168-59fcdd7c-3ea1-43a4-8766-2b3fc247da06.png)


from the gui
![image](https://user-images.githubusercontent.com/170977/235632784-e32024d7-e369-458d-9bf4-e6946b4ff1a2.png)

I goes from 18 til 4 degreeds and 'manual until midnigth'. If I repeat, same thing happens

diag:
20a86963-42e9-4066-95cb-e474bf90015b

**Comment by bwa** [comment]
This migth also be of interest

![image](https://user-images.githubusercontent.com/170977/235646274-71567265-af44-45a8-b245-c43bfe17d9da.png)

**Comment by bwa** [comment]
dbf893d4-8e42-450e-a90b-8ee9b4772283

![Uploading IMG_4340.png…]()

**Comment by bwa** [comment]
Seems to loop

![IMG_4340](https://user-images.githubusercontent.com/170977/235673340-f3096b24-5069-4483-93ef-6b1d6548a9c3.png)

**Comment by bwa** [comment]
needed to disable app, it was trying to set temperature, even when all plans was disabled

**Comment by mskg** [comment]
> This migth also be of interest
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/170977/235646274-71567265-af44-45a8-b245-c43bfe17d9da.png)
> 
> 

That happens when the other devices are not full loaded. There was no way to test that in earlier APIs.

**Comment by bwa** [comment]
I understand, and it all may be because of rc90 looks to be a bad one.

But the loop, bad temperaute, and plan goes to manual when enabled, seems to break all use

**Comment by mskg** [comment]
I check the enable disable functionality. Can you please paste your config here? It's in the settings are.

**Comment by bwa** [comment]
[heating-scheduler.txt](https://github.com/mskg/homey-heating/files/11376218/heating-scheduler.txt)
