### ISSUE TITLE
Crash since last update 

### ISSUE THREAD

**Issue by Majae95** [mskg/homey-heating#179]
Since the last update (2.0.3.) the app is crashing while startup. 

174cb99e-d040-493a-9b11-9ba13dea6b33

**Comment by mskg** [comment]
> Since the last update (2.0.3.) the app is crashing while startup. 
> 
> 
> 
> 174cb99e-d040-493a-9b11-9ba13dea6b33

The patch is already published. Just wait for the update to arrive.

Or you open the app page and install again. 2.0.6 contains the fix.

**Comment by Majae95** [comment]
Awesome, thank you so much for the rapid fix!
