### ISSUE TITLE
Thermostat verbinden

### ISSUE THREAD

**Issue by Rspart** [mskg/homey-heating#187]
hi
I can't connect a thermostat, what am I doing wrong? 
I always get the message that it hasn't found a thermostat....

Regards

**Comment by mskg** [comment]
You need a device that has the class thermostat. Can you verify if this is the case?

**Comment by Rspart** [comment]
You speak German?

Thanks for the quick answer, wow.
I have installed several thermostats. But I cannot select any of them. 
I have normal Shelly for the heating on/off. Why can't I select them? Do I have to configure them accordingly?

**Comment by mskg** [comment]
Are you talking about Shelly TRVs or another kind of Shelly devices?

**Comment by Rspart** [comment]
I have four temperature sensors
![image](https://github.com/mskg/homey-heating/assets/144152357/d488a487-583a-4a49-8c35-439f681351ec)

I would like to use the shelly 4pm for switching. But I am of the opinion that it is possible to switch on an actuator. I mean, I could just switch on a lamp instead of a heater...?

**Comment by Rspart** [comment]
Sensor 1 = SwitchBot
Sensor 2 = Shelly H&T
Sensor 3 = Philips Hue
Sensor 4 = Shelly Wand-Display
"Sensor 5" = API from Openweather

**Comment by mskg** [comment]
This app is for controlling thermostats based on schedules. 

If you want something that combines temperature readings and a actuator to a virtual thermostat, you can use https://homey.app/de-de/app/no.almli.thermostat/VThermo/. 
Also the native Shelly App has this functionality built in.

Afterwards, you could use this App to set temperatures conveniently.

**Comment by Rspart** [comment]
I'm sorry, I'm lost. 
I have to be able to read in a temperature, don't I? 
Where does it take the temperature from? 
Do you have a flow example?
