### ISSUE TITLE
Switching off a Heatingplan in a Flow

### ISSUE THREAD

**Issue by Seebub** [mskg/homey-heating#190]
I have a individual Heatingplan for each room, that reflects the use of the Room and my absence 4 days a week. I have a second Plan for each room if I have holiday or home office.  Therefore I would like to activate (that is possible) and to deactivate plans in Homey Flow. I couldnot find a command to deactivate.

**Comment by mskg** [comment]
On Nov 9, 2023, at 23:55, Seebub ***@***.***> wrote:﻿
I have a individual Heatingplan for each room, that reflects the use of the Room and my absence 4 days a week. I have a second Plan for each room if I have holiday or home office.  Therefore I would like to activate (that is possible) and to deactivate plans in Homey Flow. I couldnot find a command to deactivate.

**Comment by mskg** [comment]
![image](https://github.com/mskg/homey-heating/assets/46903097/ae495d27-b37f-4590-be9a-3dabcbcee963)
