### ISSUE TITLE
Support open windows detection

### ISSUE THREAD

**Issue by mruiter** [mskg/homey-heating#29]
Would be a great feature to have. Open window detection.
When a room / zone has door/window sensors you can select them as a open window detector for that zone and set a default close valve / lower temp in that zone.

So normal schedule is 18 degrees in the morning so me and my gf can get out of bed nicely. 
When dressed we open the window for some fresh air and leave downstairs . So the schedule in that zone will have a breakout from the default schedule to 13 or 10 degrees (whatever is set) so the valves close and heating and energy doesnt go out of the window for the time fresh air gets in.

As soon as the window in the zone is closed normal schedule wil resume.

**Comment by mskg** [comment]
Understood. You could not do that with flows directly. 

I had in my mind, that I also include an override possibility for the "Automatic" scheduler. This means, you can override the "current" temperature of a plan until end of the day. Than you can use flows (trigger on switch) to set/reset that temperate override. 

This makes the heating scheduler independent of the actors, which I would prefer. What do you think?

**Comment by mruiter** [comment]
Yes i have it now made with flows. The feature was just a easier flow less in app solution. 
More for the mediamarkt people as they are called ;)

**Comment by mskg** [comment]
So I will add that possibility (overrides, not actor listening) to the plans.

**Comment by mskg** [comment]
You can see a preview of the release notes here, there is some example: https://github.com/mskg/homey-heating/blob/feature/plan-overview/docs/releasenotes/v01-02-00.md

You can try the functionality (virtual devices) from RC3 onwards: https://github.com/mskg/homey-heating/tree/release/v1.2.0-rc3
