### ISSUE TITLE
Translation to dutch

### ISSUE THREAD

**Issue by mskg** [mskg/homey-heating#30]

**Comment by mruiter** [comment]
I would love to help you with the translation for dutch.

**Comment by mskg** [comment]
Hi @mruiter,

I did a lot of refactoring due to some other issues, mainly with iOS Safari.

If you haven't started yet, you should better begin from that branch https://github.com/mskg/homey-heating/tree/bugfix/setthermostats. I will squash merge that into master within the next days. If you already started, no problem - I will help to merge the changes into the repository.

Markus

**Comment by mskg** [comment]
I merged the changes to master.

**Comment by mskg** [comment]
I did a machine translation, which I can hardly check. Dutch is not my best 3rd language :)
Probably someone can do that for me?

**Comment by mruiter** [comment]
I should be back from traveling this weekend so should have the time now for it 👍

Verstuurd vanaf mijn iPhone

**Comment by mskg** [comment]
Be sure, that you use this branch https://github.com/mskg/homey-heating/tree/feature/plan-overview?files=1

**Comment by mskg** [comment]
First version done with #53
