### ISSUE TITLE
Target temperature on thermostat are not changing

### ISSUE THREAD

**Issue by kopanicak** [mskg/homey-heating#38]
On Homey I have installed version 2.0.2.
I have created one heating plan with shedules.
I have one device added to be applied plan (thermostat Eurotronic Spirit).
In timeline a see messages that target temperature is set, but no temperature change on device.
What do I wrong?
thanks

**Comment by mskg** [comment]
Did you use a dev or a production build? Did you install it from the store?

**Comment by mskg** [comment]
I’m currently working on the next version and I did some rework to the way how the target_temperature is set. 

I noticed, that the two methods to set the “value” (CapabilityInstance vs. DeviceManager) behave different. The DeviceManager type gives more errors and such the possibility to retry the action. I did that and the new version should be more error prone. 
Still it’s unclear to me, why the temperatures are sometimes not set.

I update the incident once it is available.

Are you able install a dev build?

**Comment by kopanicak** [comment]
yes I can test dev build.
dev build is here on GitHub?

**Comment by mskg** [comment]
Give me tomorrow to finish the small open tasks, than I will drop you a build.

**Comment by mskg** [comment]
Hi @kopanicak, you can try the build by using branch 
- https://github.com/mskg/homey-heating/tree/release/v1.1
- PR #39, or SHA af0fefa46ffe4b94375de10024859535a751ea20

[Release Notes](https://github.com/mskg/homey-heating/blob/bugfix/setthermostats/docs/releasenotes/v01-01-00.md)

**Comment by kopanicak** [comment]
it works now. target temperature is now changing on thermostat now. thanks.

but I have new problem with creating and editing shedules.
I create shedules for monday. than I copy mondays shedules to all another days.
than I edit one shedule in saturday and click on save. edited shedule is not edited but added another one.
than if i click on trash to delete wrong shedule, i cant delete it.

on "iphone se" i cant scroll down to button OK if I set the time in shedule.
i must use ipad to set the time.

**Comment by mskg** [comment]
True, fixed that and this is included in the version 1.1.1 I published to the store a couple of hours ago. 

If you don’t want to be patient: the branch is called according to the number above :)

**Comment by mskg** [comment]
For that one: 
on "iphone se" i cant scroll down to button OK if I set the time in shedule.
i must use ipad to set the time.

Could you probably open another issue and attach a screenshot to it? Don’t have such a device here.
