### ISSUE TITLE
Can't scroll down to OK in time setting

### ISSUE THREAD

**Issue by kopanicak** [mskg/homey-heating#41]
On iPhone SE (resolution like 5 and 5S) i can't scroll down a click on OK button in time setting.

I use 1.1.0 beta. In 1.0.0 beta it was OK.

![img_1208](https://user-images.githubusercontent.com/9351901/52432036-bd2c2e00-2b09-11e9-9dd1-e8e0ade46eb1.PNG)

**Comment by mskg** [comment]
Might I suggest to buy a bigger phone :)

Is this the only place where it’s broken for such small resolution?

**Comment by kopanicak** [comment]
everything else is ok on this small resolution.

I dont like big phones :D they cant fit in the pocket :D on serious work i have iPad, MacBook,... :D

**Comment by mskg** [comment]
Probably I just remove it / the OS time picker should be ok anyhow.
