### ISSUE TITLE
Suggestion: single-view schedules

### ISSUE THREAD

**Issue by lenwar** [mskg/homey-heating#44]
Hi,

I think it would be nice to be able to get an overview on a per-zone (or per radiator) basis, so the effective calculated schedule in a single view, so something in the line of:

![overzicht-temperatuur](https://user-images.githubusercontent.com/3773186/52562750-ccf48c80-2dff-11e9-81ca-b0060dd7e58f.JPG)

I'm note sure how 'readable' it would become on a phone screen, but it may be a nice extra-feature.

**Comment by mskg** [comment]
Probably D3 is a solution for the vizualization. An example: https://github.com/dk8996/Gantt-Chart
