### ISSUE TITLE
Configurable alerts

### ISSUE THREAD

**Issue by gnrk** [mskg/homey-heating#52]
### Subject of the issue
To many alerts when multiple heating plans

### Steps to reproduce
Add possibility to turn off alerts for each heating plan

### Expected behaviour
Alert only for the plans selected

### Actual behaviour
When three different plans has the same time set, but three different setpoints i get three messages. It's a little too much.

**Comment by mskg** [comment]
A general on/off for the events
- mode change
- temperature set
- temperature set error

is already part of the 1.2 branch.

**Comment by mskg** [comment]
You can try here https://github.com/mskg/homey-heating/blob/feature/plan-overview/docs/releasenotes/v01-02-00.md

Just drop me a short note if that fits?
