### ISSUE TITLE
Virtual device

### ISSUE THREAD

**Issue by Friedi1970** [mskg/homey-heating#62]
Maybe I am blind but I can’t find the way how to create the mentioned virtual device.
Could you please add a help.
Really no idea where those devices shall be :(

**Comment by mskg** [comment]
Hi, you're not :) I pushed and published the release to the store - this also included the documentation for the newest version. The version is not approved yet, but you can install the final build from https://github.com/mskg/homey-heating/tree/v1.2.0-rc19

**Comment by mskg** [comment]
Url in the old post was for the sources not the build result. I edited the post with the correct url: https://github.com/mskg/homey-heating/tree/release/v1.2.0-rc19

**Comment by mskg** [comment]
The version is published now.
