### ISSUE TITLE
- no thermostats found -

### ISSUE THREAD

**Issue by tooxe** [mskg/homey-heating#67]
VD doesn’t work. - no thermostats found -

**Comment by mskg** [comment]
Hi Tooxe, the application identifies every device that has a `set_targettemperature` capability as "thermostat."

What type is VD? 

Can you check via http://developer.athom.com/tools/devices what capabilities those devices have? Probably just post a screenshot of one fo them?

**Comment by tooxe** [comment]
Hi, it was your own VD from Home Heating Scheduler. My own with your app works fine. Probably it was something temporary. 

Skickat från min iPhone X

**Comment by mskg** [comment]
So everything works now as expected?
