### ISSUE TITLE
Additional exception for open windows/doors

### ISSUE THREAD

**Issue by Friedi1970** [mskg/homey-heating#69]
**Is your feature request related to a problem? Please describe.**
I have window and door sensors and it would be great to add those ones as exception devices.

**Describe the solution you'd like**
If a door or window is opened the thermostats should be set to the set exception temperatur. When all doors/windows of the zone are closed the temperature should be set beack to the plan temperature.

**Comment by mskg** [comment]
I understand that request and I will put it on the list. 

In the meanwhile, you could try the following:
- Add your heating plans as virtual thermostat (https://homey-heating.mskg.app/pages/device)
- Add a flow that triggers on open/close of any of the room’s windows/doors. You could do that easily with `<groups>` if there are many of them in the same zone
- On open, set temperature of associated heating plan device to, e.g. 6°
- When the switch is closed, reset the thermostat_override to automatic and you’re done.
