### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Friedi1970** [mskg/homey-heating#74]
In near future Homey get German language support.
If you like I would translate to German if you give me the needed files.

**Comment by mskg** [comment]
I‘m native German myself, but very happy if you help with the translation. I prepare a machine translation that we can adjust then :)

**Comment by Friedi1970** [comment]
Perfect 👍

**Comment by mskg** [comment]
I added the machine translation to German in this PR #98 

Feel free to change the files here, I only did a very brief review:
* https://github.com/mskg/homey-heating/blob/dependencies/locales/de.json
* https://github.com/mskg/homey-heating/blob/dependencies/src/app.json

I will drop you an URL here for the first RC build, once it is available.
