### ISSUE TITLE
No reset to temperature when in automatic mode

### ISSUE THREAD

**Issue by Friedi1970** [mskg/homey-heating#76]
**Describe the bug**
I made a setting as yu described in the FAQ. When opening a door I set the temperature of the virtual device to 6 °C and when closed the heating mode is set to automatic.
The good news is, the temperature is set to 6 °C when door is closed.
The bad news is, th mode turns back to automatic when door is closed but the temperature remains at 6 °C.

**Comment by mskg** [comment]
When you say turns back, do you mean the main heating mode or that of the thermostat you changed in beforehand?

There is two modes
* A main heating, the Flow action is called `Set heating mode`
* For each thermostat device, the Flow action is called `Set thermostat mode` (only available under the device itself)

What happens
- Main heating mode is `Automatic`
- You lower the temperature for the thermostat, it automatically goes into `Override until midnight`. The main mode stays as is.
- You set the thermostat back to `Automatic`. Now that thermostat evaluates the associated heating plan and takes the temperature from there. The main mode was `Automatic`, such it will be the temperature associated with the current time.

**Comment by Friedi1970** [comment]
OK, got you. My fault. 
Sorry for that.
