### ISSUE TITLE
Exception when sleeping does not work

### ISSUE THREAD

**Issue by Friedi1970** [mskg/homey-heating#77]
In my normal schedule I set the temperature to 20.5 °C at 4:00. I also have an exception for sleeping. When sleeping the temperatire shall switch to 16 °C.

As you may see in the insight screen shot the exception doesn't work.
![heating](https://user-images.githubusercontent.com/47818803/53859343-adefb180-3fdd-11e9-82f0-5b811d94a031.jpg)

**Comment by mskg** [comment]
Did you set the heating mode via Flow? There is no automatic, as that will always be wrong if there is more than one person living in a household :)

You can use the presence Flow actions to determine when to set the heating mode accordingly.

**Comment by Friedi1970** [comment]
Sorry, I don't understand :(
My assumption was that when everybody sleeps (presence mode) that this exception is true. Am I wrong? Do I need a flow?
Please describe a bit more precise how the sleep exception works.

**Comment by Friedi1970** [comment]
Ahhhh. Now I got it. Sometimes it take a bit longer ;)
