### ISSUE TITLE
Watchdog for recieving temperature 

### ISSUE THREAD

**Issue by Mindsuk** [mskg/homey-heating#78]
Hi Markus, it would be easier for me to explain it in german, but english is the language within github. So I would try it. 😉
I have problems with the spirits that they didn‘t recieve the temperatures that a flow or your App send to. The plan sent 18° for example, within the Homey UI I see that the Spirit is at 18°, but on the display of the Spirit is still the Old temperature. 
Is it possible to add a watchdog that check if the Spirit get the right temperature. If not, to send the Temperatur again?

Tino

**Comment by mskg** [comment]
Hi, it's actually already implemented that way - kind off. But, there is a problem in your thoughts: The application only sees what Homey reports. If you see 18° in the Homey App, and the temperature is not 18° on the thermostat - the driver failed.

-- German -- 
Das Problem ist so leider nicht so einfach lösbar. Wenn Homey 18° in der App anzeigt, dann ist das leider auch das was an diese Applikation von den Spirits berichtet wird. Wenn diese dann nicht 18° anzeigen, dann liegt es am Treiber für die Spirits. Ich habe dieselben Geräte und es funktioniert zu 95% ... manchmal leider (grundlos) nicht.
