### ISSUE TITLE
Can't install app from store

### ISSUE THREAD

**Issue by kopanicak** [mskg/homey-heating#83]
I cant' install app from store.
I've got message "This app is incompatible whit Homey. Try again.".
I have Homey version 2.0.5
In store is app version 1.2.0

**Comment by mskg** [comment]
That's the same version I'm on here. Very strange. Any more details you can share?

**Comment by kopanicak** [comment]
I'm installing apps on my new Homey (Early 2019). Other apps are installed OK.

![screen01](https://user-images.githubusercontent.com/9351901/54747732-f7d8ba00-4bcf-11e9-9ec6-bc4ab14ea727.jpg)

**Comment by kopanicak** [comment]
Can't install with CLI, too. Testing 1.2.1 alpha and 1.2.0 RC19.
![screen2](https://user-images.githubusercontent.com/9351901/54751282-bef21280-4bda-11e9-9d5f-86d23a93f7c8.jpg)

**Comment by mskg** [comment]
I noticed. They seem to have changed the schemas silently.

**Comment by mskg** [comment]
I will (try to) push this one to the store https://github.com/mskg/homey-heating/tree/release/v1.2.1-rc1

**Comment by mskg** [comment]
That’s the commit that broke the compatibility https://github.com/athombv/node-homey-lib/commit/71d4a4158e7a83666352dcb33c969be37ffc5ac1#diff-aae243c23af5c5cd3d0bc63807d56bb4

**Comment by mskg** [comment]
Homey approved the update - you can install it again.
