### ISSUE TITLE
Remote logging stops app if it cannot send 30+ messages

### ISSUE THREAD

**Issue by Friedi1970** [mskg/homey-heating#85]
Nothing to describe. The app crashes. No function!!!
Please repair...

**Comment by mskg** [comment]
"6c33d247-9cd5-402d-bacb-40e5f4085ecc" Is that you ?

**Comment by mskg** [comment]
Are you able to access the settings page?

**Comment by Friedi1970** [comment]
> "6c33d247-9cd5-402d-bacb-40e5f4085ecc" Is that you ?

Hmm. How shall I know? No idea where to see this ...

> There seems to be a problem with the remote logging functionality. You have to turn it off and it will work again.

Are you talking about the "console.re Logging" in the settings?

**Comment by mskg** [comment]
> Are you talking about the "console.re Logging" in the settings?
Yes

**Comment by Friedi1970** [comment]
I'll try it :)
