### ISSUE TITLE
Virtual thermostat: wrong mean temperature

### ISSUE THREAD

**Issue by rywr** [mskg/homey-heating#93]
Hello Markus,

great app! Thank you for your work.

I found a little bug in the virtual thermostat. Just want to let you know about.
If there are 2 davices in the group/plan, the mean temperature is calculated wrong. Only the temperature of one thermostat is devided by the numer od devices th the plan.

Here are screenshots, 1st from the virtual thermostat and the two real devices (Eurotronics Z-Wave).

![Screenshot_20190410-203436_Homey](https://user-images.githubusercontent.com/49495550/55905777-0153b180-5bd3-11e9-8a47-38ca8d82f16f.jpg)
![Screenshot_20190410-203445_Homey](https://user-images.githubusercontent.com/49495550/55905779-031d7500-5bd3-11e9-9069-e96710f9f205.jpg)
![Screenshot_20190410-203453_Homey](https://user-images.githubusercontent.com/49495550/55905781-044ea200-5bd3-11e9-84af-f55c307293fc.jpg)

Bye 
Ronny

**Comment by rywr** [comment]
Hello Markus,
after a restart of Homey all is ok now. The temperature of the virtual thermostat is the mean value like expected. Don't know what was wrong yesterday.

**Comment by mskg** [comment]
Let me check the trouble shooting logs the App collects.

**Comment by aeklo** [comment]
Confirming same issue on v1.2.1.
Restart of Homey does not solve the problem in my case.

![20190511_123625000_iOS](https://user-images.githubusercontent.com/9521066/57570248-418b9700-7400-11e9-8531-654dde1e6fd1.jpg)
![20190511_123709000_iOS](https://user-images.githubusercontent.com/9521066/57570254-46504b00-7400-11e9-88ec-4514572de64a.jpg)

**Comment by mskg** [comment]
Yes, there might be an issue related to #96. Homey does not allow creation of listeners (temperature, etc.) of devices that are currently not available. During the startup, there might be an order of execution that results in your behavior.

Could you try: 
- Disable the App (not remove) through the settings button
- Wait some minutes 
- Enable it again
- Please check if the temperature changes

**Comment by rywr** [comment]
Hello Markus,

 

yes, that could be right. It seams, the thermostat was not reachable at that time.

I think Homey (or the Eurotronics app) showed up the last known temperature in the device screen. But your app has got „0“ as value. That couel explain the wrong average value.

After a Homey restart, the Z-wave mesh seems to be refreshed and the termostats are online. I also added a Z-wave repeater for mot thermostats on 3 floors. I got no ploblems again.

 

Thank you for for investigating.

If the error appears again, I will check your suggestion and report the result. But it seams I can’t reproduce without hitting the mesh.

 

Bye

Ronny

 

Von: Markus <notifications@github.com> 
Gesendet: Samstag, 11. Mai 2019 17:26
An: mskg/homey-heating <homey-heating@noreply.github.com>
Cc: rywr <ronny.winkler@web.de>; State change <state_change@noreply.github.com>
Betreff: Re: [mskg/homey-heating] Virtual thermostat: wrong mean temperature (#93)

 

Yes, there might be an issue related to #96 <https://github.com/mskg/homey-heating/issues/96> . Homey does not allow creation of listeners (temperature, etc.) of devices that are currently not available. During the startup, there might be an order of execution that results in your behavior.

Could you try:

*	Disable the App (not remove) through the settings button
*	Wait some minutes
*	Enable it again
*	Please check if the temperature changes

**Comment by aeklo** [comment]
Confirming a restart of the app fixes the problem.
Restart of Homey does not.
Maybe add a confirmation, or re-check, of temp readings in the app then?

**Comment by mskg** [comment]
Should be fixed by #96, #95. If this is not resolved in 1.2.2 please reopen the issue.
